### ISSUE TITLE
Use storage.sync

### ISSUE THREAD

**Issue by mindplay-dk** [mjrthemes/styler#1]
Can we switch from `localStorage` to [`storage.sync`](https://developer.chrome.com/extensions/storage)?

Having my CSS and scripts persist across browsers would be sweet :-)

**Comment by mindplay-dk** [comment]
Would you accept a PR?

**Comment by mjrthemes** [comment]
Yes, you can send PR.

**Comment by mjrthemes** [comment]
Storage sync sometimes is not saving changes.

**Comment by mindplay-dk** [comment]
I haven't seen that happen, so that doesn't give me a lot to go on.

Let me know if you figure out when or where that happens, or what changes you were saving?

**Comment by mjrthemes** [comment]
Yes, of course.

Some users reporting it, and I've encountered it once.

**Comment by mindplay-dk** [comment]
Okay, I was able to reproduce it, and I know what the problem is now

> Unchecked runtime.lastError while running storage.set: This request exceeds the MAX_WRITE_OPERATIONS_PER_MINUTE quota.

The API doesn't like getting slammed with save requests - saving on every keystroke apparently is too much.

I'm unsure what to do about it though, given that `onunload` seems to be [botched](https://code.google.com/p/chromium/issues/detail?id=31262).

I'm going to see if I can make the popup talk to the background script, move the save operation into the background script, and defer the save until maybe 10 seconds after the last keystroke...

**Comment by mindplay-dk** [comment]
Well, saving after the last keystroke won't work, because the popup script will have ended by then.

So there's no other way besides `onunload` - which seems to work fine for me, although by the sound of it, there's a chance this won't work on OSX...

**Comment by mindplay-dk** [comment]
Has it been tested on OSX? Just wondering. There were a lot of comments on various Chrome issues indicating this might not work on OSX.

**Comment by mjrthemes** [comment]
Not yet.
But i won't upload this in production till someone test it on OSX.

**Comment by mjrthemes** [comment]
Also we can get another error - QUOTA_BYTES_PER_ITEM and i have no idea how to deal with it yet.

Other rates are here:
https://developer.chrome.com/extensions/storage

**Comment by mindplay-dk** [comment]
Oh, wow, there's an 8KB limit per item and a 100KB limit for the extension. Lame :-(

Well, there's [this](https://www.npmjs.com/package/chrome-storage-largesync) but I don't have time to look into it... too bad...
